name: ipl_predictor
description: "IPL Predictor - Guess Master"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/teams/
